# Enable true color and focus-events
set-option -g default-terminal "tmux-256color"
set -as terminal-features "tmux-256color:RGB"
set-option -g focus-events on

# Clipboard integration for MacOS
set -g set-clipboard on

# Fast ESC
set -sg escape-time 0

# Custom prefix key "C + space"
# set -g prefix C-space
# unbind-key C-b
# bind-key C-space send-prefix

# Custom prefix key "C + c"
set -g prefix C-c
unbind-key C-b
bind-key C-c send-prefix


# Reload Config with  prefix-+ r
unbind r 
bind r source-file ~/.tmux.conf \; display-message "Config Reloaded!"

# Vim-like movements
setw -g mode-keys vi

# Pane resizing with hjkl
bind-key -r h resize-pane -L 5
bind-key -r j resize-pane -D 5
bind-key -r k resize-pane -U 5
bind-key -r l resize-pane -R 5

# Window management prefix + w + ?
bind-key w switch-client -T prefix-w
bind-key -T prefix-w x confirm kill-window
bind-key -T prefix-w c new-window -c "#{pane_current_path}"
bind-key -T prefix-w v split-window -h -c "#{pane_current_path}"
bind-key -T prefix-w s split-window -v -c "#{pane_current_path}"
bind-key -T prefix-w m resize-pane -Z
bind-key -T prefix-w w choose-tree -w
bind-key -T prefix-w Escape switch-client -T root

# Mouse scoll 
set -g mouse on

# Start Index at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Enable modern key handling
set -g extended-keys on

# Shift+Enter → newline
bind-key -n S-Enter send-keys C-j

# Plugins
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'

# Refresh Indecies Automatically
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

